-- ========================================
-- COMPLETE MERITOMATCH DATABASE MIGRATION
-- ========================================
-- Run this file in your self-hosted Supabase SQL Editor

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create specific types
CREATE TYPE intent_type AS ENUM ('Relationship', 'Fun', 'Chat');
CREATE TYPE like_status AS ENUM ('pending', 'rejected', 'accepted');

-- ========================================
-- PROFILES Table
-- ========================================
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  email text,
  semester int CHECK (semester >= 1 AND semester <= 8),
  study_field text,
  intent intent_type,
  bio text,
  avatar_url text,
  nickname text,
  created_at timestamptz DEFAULT now()
);

-- Add admin and banned columns immediately after table creation
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS is_admin boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS is_banned boolean DEFAULT false;

-- Enable RLS on Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profile Policies
CREATE POLICY "Public profiles are viewable by everyone"
  ON profiles FOR SELECT
  USING ( true );

CREATE POLICY "Users can insert their own profile"
  ON profiles FOR INSERT
  WITH CHECK ( auth.uid() = id );

CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE
  USING ( auth.uid() = id );

CREATE POLICY "Admins can update any profile"
  ON profiles FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND is_admin = true
    )
  );

-- ========================================
-- LIKES Table
-- ========================================
CREATE TABLE public.likes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_user uuid REFERENCES public.profiles(id) NOT NULL,
  to_user uuid REFERENCES public.profiles(id) NOT NULL,
  status like_status DEFAULT 'pending',
  created_at timestamptz DEFAULT now(),
  UNIQUE(from_user, to_user)
);

-- Enable RLS on Likes
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;

-- Likes Policies
CREATE POLICY "Users can see likes they sent or received"
  ON likes FOR SELECT
  USING ( auth.uid() = from_user OR auth.uid() = to_user );

CREATE POLICY "Users can insert their own likes"
  ON likes FOR INSERT
  WITH CHECK ( auth.uid() = from_user );

CREATE POLICY "Users can update likes involved in"
  ON likes FOR UPDATE
  USING ( auth.uid() = from_user OR auth.uid() = to_user );

-- ========================================
-- MATCHES Table
-- ========================================
CREATE TABLE public.matches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_a uuid REFERENCES public.profiles(id) NOT NULL,
  user_b uuid REFERENCES public.profiles(id) NOT NULL,
  user_a_last_read timestamptz DEFAULT now(),
  user_b_last_read timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now()
);

-- Enable RLS on Matches
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;

-- Matches Policies
CREATE POLICY "Users can see their own matches"
  ON matches FOR SELECT
  USING ( auth.uid() = user_a OR auth.uid() = user_b );

CREATE POLICY "Server side match creation"
  ON matches FOR INSERT
  WITH CHECK ( true );

-- ========================================
-- MESSAGES Table
-- ========================================
CREATE TABLE public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id bigint REFERENCES public.matches(id) ON DELETE CASCADE NOT NULL,
  sender_id uuid REFERENCES public.profiles(id) NOT NULL,
  content text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Enable RLS on Messages
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Messages Policies
CREATE POLICY "Users can see messages in their matches"
  ON messages FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM matches m
      WHERE m.id = messages.match_id
      AND (m.user_a = auth.uid() OR m.user_b = auth.uid())
    )
  );

CREATE POLICY "Users can insert messages in their matches"
  ON messages FOR INSERT
  WITH CHECK (
    auth.uid() = sender_id
    AND EXISTS (
      SELECT 1 FROM matches m
      WHERE m.id = messages.match_id
      AND (m.user_a = auth.uid() OR m.user_b = auth.uid())
    )
  );

-- ========================================
-- BLOCKED USERS Table
-- ========================================
CREATE TABLE public.blocked_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blocker_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  blocked_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  created_at timestamptz DEFAULT now(),
  UNIQUE(blocker_id, blocked_id)
);

-- Enable RLS
ALTER TABLE public.blocked_users ENABLE ROW LEVEL SECURITY;

-- Blocked Users Policies
CREATE POLICY "Users can see their own blocks"
  ON blocked_users FOR SELECT
  USING ( auth.uid() = blocker_id );

CREATE POLICY "Users can block others"
  ON blocked_users FOR INSERT
  WITH CHECK ( auth.uid() = blocker_id );

CREATE POLICY "Users can unblock"
  ON blocked_users FOR DELETE
  USING ( auth.uid() = blocker_id );

-- ========================================
-- REPORTS Table
-- ========================================
CREATE TABLE public.reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  reported_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  reason text NOT NULL,
  evidence_url text,
  chat_log text,
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'resolved', 'dismissed')),
  created_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- Reports Policies
CREATE POLICY "Users can submit reports"
  ON reports FOR INSERT
  WITH CHECK ( auth.uid() = reporter_id );

CREATE POLICY "Users can see their own reports"
  ON reports FOR SELECT
  USING ( auth.uid() = reporter_id );

-- Admin policy (requires is_admin column)
CREATE POLICY "Admins can see all reports"
  ON reports FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND is_admin = true
    )
  );

CREATE POLICY "Admins can update reports"
  ON reports FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND is_admin = true
    )
  );

-- ========================================
-- Note: Banning is handled via is_banned column in profiles table
-- ========================================
-- Realtime publication
-- ========================================
ALTER PUBLICATION supabase_realtime ADD TABLE messages;

-- ========================================
-- Trigger to prevent blocked users from messaging
-- ========================================
CREATE OR REPLACE FUNCTION prevent_blocked_messages()
RETURNS TRIGGER AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM blocked_users
    WHERE (blocker_id = NEW.sender_id AND blocked_id IN (
      SELECT user_a FROM matches WHERE id = NEW.match_id
      UNION
      SELECT user_b FROM matches WHERE id = NEW.match_id
    ))
    OR (blocked_id = NEW.sender_id AND blocker_id IN (
      SELECT user_a FROM matches WHERE id = NEW.match_id
      UNION
      SELECT user_b FROM matches WHERE id = NEW.match_id
    ))
  ) THEN
    RAISE EXCEPTION 'Cannot send message to blocked user';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER check_blocked_before_message
  BEFORE INSERT ON messages
  FOR EACH ROW
  EXECUTE FUNCTION prevent_blocked_messages();

-- ========================================
-- MIGRATION COMPLETE
-- ========================================
-- Next steps:
-- 1. Set an admin user: UPDATE profiles SET is_admin = true WHERE email = 'your@email.com';
-- 2. Test authentication
-- 3. Update your Next.js .env.local with the new Supabase URL and ANON_KEY
