-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create specific types
create type intent_type as enum ('Relationship', 'Fun', 'Chat');
create type like_status as enum ('pending', 'rejected', 'accepted');

-- PROFILES Table
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  semester int check (semester >= 1 and semester <= 8),
  study_field text,
  intent intent_type,
  bio text,
  avatar_url text,
  created_at timestamptz default now()
);

-- Enable RLS on Profiles
alter table public.profiles enable row level security;

-- Profile Policies
create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

create policy "Users can insert their own profile"
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );

-- LIKES Table
create table public.likes (
  id bigint generated by default as identity primary key,
  from_user uuid references public.profiles(id) not null,
  to_user uuid references public.profiles(id) not null,
  status like_status default 'pending',
  created_at timestamptz default now(),
  unique(from_user, to_user)
);

-- Enable RLS on Likes
alter table public.likes enable row level security;

-- Likes Policies
create policy "Users can see likes they sent or received"
  on likes for select
  using ( auth.uid() = from_user or auth.uid() = to_user );

create policy "Users can insert their own likes"
  on likes for insert
  with check ( auth.uid() = from_user );

create policy "Users can update likes involved in"
  on likes for update
  using ( auth.uid() = from_user or auth.uid() = to_user );

-- MATCHES Table
create table public.matches (
  id bigint generated by default as identity primary key,
  user_a uuid references public.profiles(id) not null,
  user_b uuid references public.profiles(id) not null,
  created_at timestamptz default now()
);

-- Enable RLS on Matches
alter table public.matches enable row level security;

-- Matches Policies
create policy "Users can see their own matches"
  on matches for select
  using ( auth.uid() = user_a or auth.uid() = user_b );

create policy "Server side match creation"
  on matches for insert
  with check ( true ); -- Usually handled by server logic or triggers, but for simplicity allowing insert if authorized (refined logic below)

-- MESSAGES Table
create table public.messages (
  id bigint generated by default as identity primary key,
  match_id bigint references public.matches(id) not null,
  sender_id uuid references public.profiles(id) not null,
  content text not null,
  created_at timestamptz default now()
);

-- Enable RLS on Messages
alter table public.messages enable row level security;

-- Messages Policies
create policy "Users can see messages in their matches"
  on messages for select
  using (
    exists (
      select 1 from matches m
      where m.id = messages.match_id
      and (m.user_a = auth.uid() or m.user_b = auth.uid())
    )
  );

create policy "Users can insert messages in their matches"
  on messages for insert
  with check (
    auth.uid() = sender_id
    and exists (
      select 1 from matches m
      where m.id = messages.match_id
      and (m.user_a = auth.uid() or m.user_b = auth.uid())
    )
  );

-- Realtime publication
alter publication supabase_realtime add table messages;

-- FUNCTION to handle new user signup (Optional automatic profile creation trigger, but we are doing explicit onboarding)
-- We will stick to manual profile creation in the onboarding flow as per requirements.

